### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by Rahulsunny11** [sushrutt12/scrapingimages#1]
Hey, I tried running your scrip[t but i got the following error. please help me
`  File "c:\users\admin\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\ADMIN\Downloads\Compressed\gettyimages_scrapingimages-master\scrapingimages-master\imagecrawler\imagecrawler\spiders\crawler.py", line 27, in parse
    yield scrapy.Request("https://www.gettyimages.com"+next.xpath("@href").extract_first(), self.parse)
TypeError: can only concatenate str (not "NoneType") to str`

thanks

**Comment by sushrutt12** [comment]
> Hey, I tried running your scrip[t but i got the following error. please help me
> ` File "c:\users\admin\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable for r in iterable: File "C:\Users\ADMIN\Downloads\Compressed\gettyimages_scrapingimages-master\scrapingimages-master\imagecrawler\imagecrawler\spiders\crawler.py", line 27, in parse yield scrapy.Request("https://www.gettyimages.com"+next.xpath("@href").extract_first(), self.parse) TypeError: can only concatenate str (not "NoneType") to str`
> 
> thanks

Hi @Rahulsunny11 ,

The error suggests that there was no `@href` in the xpath of the `next` variable. 

It could be for any reason some of which are given below:

- GettyImages changed their page / DOM structure
- There was no link to the page
- GettyImages flagged your IP for consecutive computer generated requests (botting)
- your search query didnt have any more pages

A simple if statement to check if the element exists should solve the problem.
